export const vouchPageCopy = {
  loadingDetailsLabel: "Loading Vouch details",
  create: {
    eyebrow: "For business owners",
    title: "Create a Vouch",
    pageTitle: "New Vouch",
    pageBody:
      "Set the appointment and protected amount, review the terms, then pay the protocol fee to create the customer authorization link.",
    blockedTitle: "Finish setup to continue",
    blockedActionLabel: "Return to dashboard",
    onboardingEyebrow: "Stripe setup required",
    onboardingTitle: "Finish Stripe setup to create Vouches",
    onboardingBody:
      "Your business must finish Stripe onboarding and be ready to accept charges and payouts before you can create a Vouch.",
    detailsHeader: "Vouch details",
    readyBody:
      "Start with the amount, appointment time, and confirmation window. These terms become the basis for the Vouch protocol before commitment.",
    appointmentFieldLabel: "Appointment date and time",
    amountFieldLabel: "Protected amount",
    steps: {
      disclaimer: "Disclaimer",
      appointment: "Appointment",
      review: "Review",
    },
    appointmentHelp:
      "Create the Vouch within 24 hours of the appointment. Both people can confirm from one hour before until one hour after the appointment.",
    reviewTitle: "Review your Vouch",
    reviewBody:
      "Review immutable terms before creation. The Vouch fee is paid by the merchant through hosted Stripe checkout at committed creation.",
    feeTitle: "Creation fee",
    feeBody:
      "The Vouch fee is due when the merchant commits the Vouch. Stripe hosts the payment step and returns provider state for reconciliation.",
    hostedPaymentTitle: "Stripe-hosted payment step",
    hostedPaymentBody:
      "Vouch does not host card, bank, identity, payout, or payment authorization forms. Stripe owns those hosted surfaces.",
    disclaimerLabel:
      "I understand this Vouch becomes immutable after commitment and the merchant Vouch fee is paid through Stripe at creation.",
    amountPlaceholder: "250.00",
    progressLabel: "Progress steps",
    openingCheckoutAction: "Opening Checkout",
    commitAction: "Pay protocol fee",
    reviewEyebrow: "Review",
    reviewDetailsTitle: "Vouch details",
    appointmentLabel: "Appointment",
    protocolFeeLabel: "Protocol fee",
    protocolFeeRate: "5% minimum $5",
    dueNowLabel: "Business pays now",
    afterPayment:
      "After the business pays the protocol fee, the Vouch detail page will show a Stripe link for the customer to authorize the protected amount.",
    disclaimerBody:
      "Vouch coordinates the confirmation workflow. Stripe handles the business payment, customer authorization, and payment processing. Vouch does not hold customer funds.",
    disclaimerAgreement: "I agree to the",
    disclaimerLinkLabel: "Disclaimer",
    errors: {
      create: "Unable to create this Vouch.",
      checkout: "Stripe Checkout could not be opened. Try again.",
    },
    ruleTitle: "Outcome follows confirmation state.",
    ruleBody:
      "Both participants confirm presence inside the configured window for release. Anything else resolves through provider-backed non-capture, void, refund, cancel, or expiration state.",
  },
  detail: {
    eyebrow: "Participant ledger",
    title: "Vouch",
    heroBody:
      "commitment for {appointmentLabel}. Outcome follows bilateral confirmation inside the window.",
    labels: {
      merchant: "Merchant",
      customer: "Customer",
      amount: "Amount",
      window: "Window",
      appointment: "Appointment",
      opens: "Opens",
      expires: "Expires",
      vouchAmount: "Vouch amount",
      merchantReceives: "Merchant receives",
      customerAuthorizes: "Customer authorizes",
      status: "Status",
      role: "Role",
    },
    sections: {
      confirmation: "Confirmation",
      schedule: "Schedule",
      payment: "Payment details",
      timeline: "Timeline",
      rule: "Rule",
      bottomCallout: "Protocol checkpoint",
    },
    states: {
      bothConfirmed: "Both confirmed",
      waiting: "Waiting",
      confirmed: "Confirmed",
      notConfirmed: "Not confirmed",
      noTimeline: "No participant-safe events recorded yet.",
    },
    termsTitle: "Immutable terms",
    actionsTitle: "Safe actions",
    providerBoundary:
      "Provider payment, identity, payout, and payment method steps stay on hosted provider surfaces. Vouch only shows safe state and next actions.",
    oneSidedRule: "One-sided confirmation never releases funds.",
    ruleDescription:
      "Both confirm in time and capture can proceed. Otherwise provider state determines void, refund, or non-capture.",
    bottomCalloutTitle: "The Vouch object is the operating center.",
    bottomCalloutBody:
      "Terms, payment state, confirmation state, and participant-safe timeline stay together here. No separate dispute, message, or manual settlement surface exists.",
    confirmDrawerTitle: "Confirm presence",
    confirmDrawerBody:
      "Submit the other participant's current code only if you were present inside the confirmation window.",
    confirmDrawerTrigger: "Open confirmation",
    document: {
      eyebrow: "Vouch detail",
      criticalStatusLabel: "Critical Vouch status",
      paymentEyebrow: "Payment",
      paymentTitle: "Authorization",
      scheduleEyebrow: "Schedule",
      scheduleTitle: "Window",
      windowStatus: "Window status",
      pending: "Pending",
      windowRule: "Confirmation is only valid inside the scheduled window.",
      timelineEyebrow: "Timeline",
      timelineTitle: "Next action",
      presenceEyebrow: "Presence",
      presenceTitle: "Confirmation",
      settlement: "Settlement",
    },
    confirmationForm: {
      codePlaceholder: "000000",
      closedTitle: "Confirmation closed",
      closedBody:
        "The confirmation window is closed. Codes and confirmation controls are no longer valid.",
      codeExchange: "Code exchange",
      codeHelp:
        "Keep your code visible until the window closes. The other participant needs it even after you confirm.",
      yourCode: "Your code",
      copied: "Copied",
      copy: "Copy",
      otherCode: "Other participant code",
      confirming: "Confirming...",
      confirm: "Confirm my presence",
      confirmedHelp:
        "Your side is confirmed. Keep this code available for the other participant until the window expires.",
      errors: {
        unavailable: "This participant is already confirmed or the confirmation window is closed.",
        invalid: "Enter the other participant's 6-digit code.",
        ownCode: "That is your code. Enter the other participant's code.",
        failed: "Confirmation failed. Check the code and try again.",
      },
      success: "Confirmed. This code stays visible until the window expires.",
    },
    checkoutShare: {
      subject: "Vouch payment authorization",
      request: "Please authorize your Vouch payment through Stripe:",
      authorizationRule:
        "The payment is authorized through Stripe. Funds are released only after both participants complete the required Vouch confirmation step.",
      fallbackHost: "Stripe Checkout",
      eyebrow: "Customer checkout",
      hostedLabel: "Stripe hosted",
      copyLinkAriaLabel: "Copy checkout link",
      copyMessageAriaLabel: "Copy checkout message",
      emailAriaLabel: "Email checkout message",
      textAriaLabel: "Text checkout message",
      shareAriaLabel: "Share checkout message",
      link: "Link",
      copy: "Copy",
      email: "Email",
      text: "Text",
      share: "Share",
      whatsapp: "Send with WhatsApp",
      copied: "Copied to clipboard.",
    },
  },
  providerRedirects: {
    connect: {
      title: "Finish your Stripe setup",
      consequence:
        "Complete your secure Stripe setup so your business is ready to create Vouches and receive payouts.",
      context:
        "Stripe will guide you through the details it needs for verification, banking, and payout access.",
      finePrint: "You'll return to Vouch when you're done.",
    },
    connectDashboard: {
      title: "Open your Stripe dashboard",
      consequence:
        "Manage your connected Stripe account, review payments, and access payout details.",
      context:
        "Stripe hosts your connected account dashboard and keeps payment and payout controls secure.",
      finePrint: "You'll leave Vouch and continue in your Stripe dashboard.",
      actionLabel: "Open Stripe dashboard",
    },
  },
  confirm: {
    eyebrow: "Presence confirmation",
    body: "Confirm that you were present. Both parties must confirm within the window for funds to release.",
    labels: {
      vouchStatus: "Vouch status",
      created: "Created",
      started: "Started",
      deadline: "Deadline",
      payer: "Payer",
      payeeYou: "Payee (You)",
      participant: "participant",
    },
    sections: {
      window: "Confirmation window",
      status: "Confirmation status",
      yourConfirmation: "Your confirmation",
    },
    states: {
      confirmed: "Confirmed",
      notConfirmed: "Not confirmed",
      waiting: "Waiting for the other party if needed.",
    },
    fallbackCreatedAt: "May 24, 2025 at 1:45 PM",
    countdownPlaceholder: "01 : 23 : 47",
    deadlineConsequence:
      "If you don't confirm by the deadline, payment is refunded according to provider state.",
    confirmationBody: "By confirming, you state that you were present during the meeting window.",
    confirmAction: "Confirm I was present",
    irreversible: "This action cannot be undone",
  },
  share: {
    eyebrow: "Invite",
    title: "Share this Vouch",
    body: "Invite the other party to accept this commitment. They'll need to sign in or create an account.",
    inviteLinkTitle: "Invite link",
    inviteLinkBody: "Anyone with this link can view and accept this Vouch.",
    copyLink: "Copy link",
    sendInvitationTitle: "Send invitation",
    sendInvitationBody: "Send an email invitation directly.",
    sendInvitation: "Send invitation",
    emailPlaceholder: "email@example.com",
    summaryTitle: "Vouch summary",
    pending: "Pending",
    amountCurrency: "USD",
    inviteUrl: "https://vouch.com/invite/abc123xyz789",
    rule: "Funds release only after both parties confirm presence within the window.",
    summaryRows: [
      ["From", "jordan@client.com"],
      ["For", "you"],
      ["Label", "Consulting call"],
      ["Meeting window", "May 24, 2025 - 4:00 PM - 6:00 PM"],
    ],
  },
  list: {
    eyebrow: "Participant ledger",
    defaultTitle: "Vouches",
    body: "Participant-scoped Vouches only.",
    create: "Create Vouch",
    emptyTitle: "No Vouches yet.",
    emptyBody:
      "Create a Vouch to back an appointment or in-person agreement with a clear payment commitment. Both parties confirm presence; otherwise refund, void, or non-capture.",
    nextAction: "Next action",
    emptyActionBody: "Start with amount, meeting window, confirmation deadline, and recipient.",
  },
  invite: {
    invalidTitle: "This invite is no longer available.",
    eyebrow: "Customer invite",
    title: "You've been invited",
    body: "Review the Vouch details below. Finish setup and accept to lock in this commitment.",
    secureTitle: "Secure and neutral",
    secureBody:
      "Payments are processed by Stripe. Vouch does not hold funds and does not judge outcomes.",
    acceptTitle: "Accept this Vouch",
    steps: ["Review", "Setup", "Accept"],
    unsignedNotice: {
      title: "Create your account to continue",
      body: "Your invite is saved. Sign in or create an account before accepting.",
    },
    ineligibleNotice: {
      title: "Complete the steps below to accept",
      body: "You must be verified and ready to receive funds.",
    },
    readyNotice: {
      title: "Ready to accept",
      body: "Both parties must confirm presence after acceptance.",
    },
    readinessItems: [
      "Identity verification",
      "18+ verification",
      "Payout setup",
      "Terms acceptance",
    ],
    verified: "Verified",
    reviewTerms: "Review terms",
    nextTitle: "What happens next?",
    nextBody:
      "After you accept, both parties must confirm within the window. If both confirm, funds release. If not, the payment is refunded according to provider state.",
    signUp: "Sign up",
    signIn: "Sign in",
    reviewSetup: "Review setup",
    accept: "Accept this Vouch",
    summaryTitle: "Vouch summary",
    amountCurrency: "USD",
    summaryRows: {
      for: "you",
      label: "Consulting call",
    },
    summaryRule: "Both parties must confirm before funds release.",
  },
} as const
