import {
  OPEN_VOUCH_STATUS_VALUES,
  PARTICIPANT_ROLE_VALUES,
  TERMINAL_VOUCH_STATUS_VALUES,
} from "@/lib/vouch/constants"

export const FINAL_VOUCH_STATUSES = TERMINAL_VOUCH_STATUS_VALUES
export const ACTIVE_VOUCH_STATUSES = OPEN_VOUCH_STATUS_VALUES
export const PARTICIPANT_ROLES = PARTICIPANT_ROLE_VALUES
